// Imports a tour-list page from india-tourism.net (a category with its tours, e.g.
// india-golden-triangle-tour.htm or itineraries.htm) into data/tour-lists/<original-name>.js.
// Wording is copied as-is (only runs of whitespace collapsed); bold stays bold.
//
//   node scripts/import-list.js [--dir folder] rajasthan-tours.html ...
const fs = require('fs');
const path = require('path');
const { txt, seg, pageInfo, mainColumn, J, crumbsJs, run } = require('./lib');

const OUT = path.join(__dirname, '..', 'data', 'tour-lists');

function parse(h) {
  const info = pageInfo(h);
  const main = mainColumn(h);

  // Walk the page in order: paragraphs, group headings (h3 in td.itititle) and tours (h4.subitititle)
  const intro = [], outro = [], groups = [];
  let group = null;
  // A tour runs from its h4 up to the next tour/group/end of table; its route and duration
  // may sit in a <span>, in <h5>/<h6> or in a <p> right after the name.
  const tokens = /<(?:p|div align="justify")[^>]*>([\s\S]*?)<\/(?:p|div)>|<td class="itititle"[^>]*>\s*<h3[^>]*>([\s\S]*?)<\/h3>|<h4 class="subitititle"[^>]*>([\s\S]*?)<\/h4>([\s\S]*?)(?=<h4 class="subitititle"|<td class="itititle"|<\/table>|$)/g;
  let m, seenTour = false;
  while ((m = tokens.exec(main))) {
    if (m[1] !== undefined) {
      const s = seg(m[1]);
      if (s.length) (seenTour ? outro : intro).push(s);
    } else if (m[2] !== undefined) {
      const a = m[2].match(/href="([^"]+)"/);
      group = { title: txt(m[2]), file: a ? a[1] : '', tours: [] };
      groups.push(group);
    } else {
      seenTour = true;
      if (!txt(m[3])) continue;                                     // empty heading on the original
      if (!group) { group = { title: '', file: '', tours: [] }; groups.push(group); }
      const a = m[3].match(/href="([^"]+)"/);
      const lines = m[4].split(/<br\s*\/?>|<\/h5>|<\/h6>|<\/p>/i).map(txt).filter(Boolean);
      const di = lines.findIndex(l => /\bnights?\b|\bdays?\b/i.test(l));
      group.tours.push({
        name: txt(m[3]),
        file: a ? a[1] : '',
        route: (di > 0 ? lines.slice(0, di) : di < 0 ? lines : []).join(' '),
        duration: di >= 0 ? lines.slice(di).join(' ') : ''
      });
    }
  }
  return { info, intro, outro, groups: groups.filter(g => g.tours.length || g.title) };
}

function write(file, html) {
  const base = file.replace(/\.html?$/i, '');
  const { info, intro, outro, groups } = parse(html);
  const groupsJs = groups.map(g => `    {
      title: ${JSON.stringify(g.title)},
      href: ${g.file ? `site.link(${JSON.stringify(g.file)})` : "''"},
      tours: [
${g.tours.map(t => `        { name: ${JSON.stringify(t.name)}, href: ${t.file ? `site.link(${JSON.stringify(t.file)})` : "''"}, route: ${JSON.stringify(t.route)}, duration: ${JSON.stringify(t.duration)} }`).join(',\n')}
      ]
    }`).join(',\n');
  const out = `// Content of https://india-tourism.net/${file} — generated by scripts/import-list.js.
// Wording unchanged (only runs of whitespace collapsed). Bold parts are bold on the original too.
// Served at /${base}
const site = require('../site');

module.exports = {
  file: ${JSON.stringify(file)},
  url: ${JSON.stringify('/' + base)},
  title: ${JSON.stringify(info.title)},
  description: ${JSON.stringify(info.description)},
  keywords: ${JSON.stringify(info.keywords)},
  heroSrc: site.IMG(${JSON.stringify(info.hero)}),
  heroAlt: ${JSON.stringify(info.heroAlt || info.heading)},
  nav: site.nav('India Tours', ${base === 'itineraries'}),
  footCols: site.footCols(),
  listings: require('../listings'),

  // Original: ${info.breadcrumbText}
  breadcrumb: [
${crumbsJs(info.breadcrumb)}
  ],
  heading: ${JSON.stringify(info.heading)},

  intro: ${J(intro)},

  groups: [
${groupsJs}
  ],

  outro: ${J(outro)}
};
`;
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, base + '.js'), out);
  const n = groups.reduce((s, g) => s + g.tours.length, 0);
  const noDur = groups.flatMap(g => g.tours).filter(t => !t.duration).length;
  console.log(`${file}: "${info.heading}" | ${groups.length} group(s), ${n} tours | intro ${intro.length}p, outro ${outro.length}p${noDur ? ' | ' + noDur + ' tour(s) without duration' : ''}`);
}

run(write);
