// Imports a text page from india-tourism.net (travel guide, regions, testimonials, visa info, ...)
// into data/articles/<original-name>.js. The page content is kept as cleaned-up HTML: headings,
// paragraphs, lists, tables, bold, images and links keep their wording; the old styling and
// scripts are dropped. Links and images are rewritten to local addresses when the page renders.
//
//   node scripts/import-article.js [--dir folder] weather.htm ...
const fs = require('fs');
const path = require('path');
const { pageInfo, mainColumn, J, crumbsJs, run } = require('./lib');

const OUT = path.join(__dirname, '..', 'data', 'articles');

const KEEP = {
  p: [], br: [], hr: [], h2: [], h3: [], h4: [], h5: [], h6: [], ul: [], ol: [], li: [], blockquote: [],
  strong: [], b: [], em: [], i: [], u: [],
  a: ['href', 'title', 'id'], img: ['src', 'alt'],
  table: [], thead: [], tbody: [], tfoot: [], tr: [], td: ['colspan', 'rowspan'], th: ['colspan', 'rowspan']
};

// Cloudflare hides e-mail addresses on the original ("[email protected]" + a hex code decoded by a
// script). Decode them back to the real address.
const cfDecode = hex => { const k = parseInt(hex.slice(0, 2), 16); let s = ''; for (let i = 2; i < hex.length; i += 2) s += String.fromCharCode(parseInt(hex.slice(i, i + 2), 16) ^ k); return s; };

function clean(html) {
  const mail = hex => { const e = cfDecode(hex); return '<a href="mailto:' + e + '">' + e + '</a>'; };
  let s = html
    .replace(/<a[^>]*data-cfemail="([0-9a-f]+)"[^>]*>[\s\S]*?<\/a>/gi, (m, hex) => mail(hex))
    .replace(/<a[^>]*href="\/cdn-cgi\/l\/email-protection#([0-9a-f]+)"[^>]*>[\s\S]*?<\/a>/gi, (m, hex) => mail(hex))
    .replace(/<span[^>]*data-cfemail="([0-9a-f]+)"[^>]*>[\s\S]*?<\/span>/gi, (m, hex) => cfDecode(hex))
    .replace(/<!--[\s\S]*?-->/g, '')
    .replace(/<(script|style|noscript|iframe|form|select|textarea)[\s\S]*?<\/\1>/gi, '')
    .replace(/<h1[^>]*>[\s\S]*?<\/h1>/i, '')                  // shown in the page header instead
    .replace(/<a\b([^>]*?)\sname="([^"]+)"/gi, '<a$1 id="$2"');  // in-page anchors (<a name="A">) keep working
  s = s.replace(/<(\/?)([a-z0-9]+)([^>]*)>/gi, (m, close, tag, attrs) => {
    tag = tag.toLowerCase();
    if (tag === 'h1') tag = 'h2';
    if (!KEEP[tag]) return tag === 'div' || tag === 'section' ? (close ? '\n' : '') : '';   // drop the tag, keep its text
    if (close) return '</' + tag + '>';
    const kept = KEEP[tag].map(a => {
      const v = attrs.match(new RegExp('\\s' + a + '\\s*=\\s*"([^"]*)"', 'i')) || attrs.match(new RegExp('\\s' + a + "\\s*=\\s*'([^']*)'", 'i'));
      return v ? ' ' + a + '="' + v[1].replace(/"/g, '&quot;') + '"' : '';
    }).join('');
    return '<' + tag + kept + (tag === 'img' || tag === 'br' || tag === 'hr' ? ' /' : '') + '>';
  });
  return s
    .replace(/<p>\s*(?:&nbsp;|\s|<br \/>)*<\/p>/g, '')                      // empty paragraphs
    .replace(/<a href="[^"]*">\s*<\/a>/g, '')
    .replace(/[ \t]+/g, ' ').replace(/\s*\n\s*/g, '\n').replace(/\n{2,}/g, '\n')
    .replace(/<table>/g, '<div class="table-wrap"><table>').replace(/<\/table>/g, '</table></div>')
    .trim();
}

function write(file, html) {
  const base = file.replace(/\.html?$/i, '');
  const info = pageInfo(html);
  const body = clean(mainColumn(html));
  const out = `// Content of https://india-tourism.net/${file} — generated by scripts/import-article.js.
// Wording unchanged; the original's markup is reduced to plain headings, paragraphs, lists,
// tables, images and links. Links/images are made local when rendered (site.rewriteHtml).
// Served at /${base}
const site = require('../site');

module.exports = {
  file: ${JSON.stringify(file)},
  url: ${JSON.stringify('/' + base)},
  title: ${JSON.stringify(info.title)},
  description: ${JSON.stringify(info.description)},
  keywords: ${JSON.stringify(info.keywords)},
  heroSrc: site.IMG(${JSON.stringify(info.hero)}),
  heroAlt: ${JSON.stringify(info.heroAlt || info.heading)},
  nav: site.nav(${base === 'testimonials' ? "'Testimonials'" : "''"}, ${base === 'testimonials'}),
  footCols: site.footCols(),
  listings: require('../listings'),

  // Original: ${info.breadcrumbText}
  breadcrumb: [
${crumbsJs(info.breadcrumb)}
  ],
  heading: ${JSON.stringify(info.heading)},

  html: ${JSON.stringify(body)}
};
`;
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, base + '.js'), out);
  const counts = ['h2', 'h3', 'h4', 'p', 'li', 'table', 'img', 'a'].map(t => t + ':' + (body.match(new RegExp('<' + t + '[\\s>/]', 'g')) || []).length).join(' ');
  console.log(`${file}: "${info.heading}" | ${counts}`);
}

run(write);
