// Imports a tour itinerary page from india-tourism.net into data/tours/<original-name>.js.
// The wording is copied as-is (only runs of whitespace are collapsed); bold stays bold.
// The page is then served at the original file name without the extension.
//
//   node scripts/import-tour.js golden_triangle_packages.html [more.html ...]
//   node scripts/import-tour.js --file saved-page.html golden_triangle_packages.html
const fs = require('fs');
const path = require('path');

const { dec, txt, seg } = require('./lib');

const OUT = path.join(__dirname, '..', 'data', 'tours');

function parse(h, file) {
  const meta = n => { const m = h.match(new RegExp('<meta name="' + n + '" content="([^"]*)"')); return m ? dec(m[1]) : ''; };
  const main = h.slice(h.indexOf('touritneraryblock'), h.indexOf('touritneraryright'));
  const need = (m, what) => { if (!m) throw new Error('no ' + what); return m[1]; };
  const one = (re, what) => need(main.match(re), what);

  const days = main.split('<div class="tour-day">').slice(1).map(c => c.split('<div class="tour-details-card">')[0])
    .filter(d => /class="day-number"/.test(d))   // a few originals contain an empty day block
    .map(d => {
    const note = d.match(/<div class="Notes">([\s\S]*?)<\/div>/);
    const eta = d.match(/<span class="ETA">([\s\S]*?)<\/span>/);
    const paras = [...d.matchAll(/<p>([\s\S]*?)<\/p>/g)].map(m => seg(m[1])).filter(p => p.length);
    return {
      day: txt(need(d.match(/<span class="day-number">([\s\S]*?)<\/span>/), 'day number')),
      title: txt(need(d.match(/<h3[^>]*>([\s\S]*?)<\/h3>/), 'day title')),
      eta: eta ? txt(eta[1]) : '',
      paras,
      note: note ? seg(note[1]) : null
    };
  });

  const card = main.slice(main.indexOf('<div class="tour-details-card">'), main.indexOf('tour-eqry') > -1 ? main.indexOf('tour-eqry') : undefined);
  const details = card.split(/(?=<h3[\s>])/).filter(b => /<h3[\s>]/.test(b)).map(b => {
    const p = b.match(/<\/h3>\s*<p>([\s\S]*?)<\/p>/);
    return { title: txt(need(b.match(/<h3[^>]*>([\s\S]*?)<\/h3>/), 'details title')), text: p ? txt(p[1]) : '', items: [...b.matchAll(/<li>([\s\S]*?)<\/li>/g)].map(x => seg(x[1])) };
  }).filter(b => b.text || b.items.length);   // a couple of originals repeat a heading with nothing under it

  // The enquiry button: "Enquire Now" on most pages, "Book This Tour" / "Tour Enquiry" on some
  const eq = main.match(/<a href="([^"]*)"\s*class="tour-eqry"[\s\S]*?>([\s\S]*?)<\/a>/)
    || main.match(/<a href="([^"]*(?:enquiry|helpmetours)[^"]*\.aspx[^"]*)"[^>]*>([\s\S]*?)<\/a>/i);
  const bc = need(h.match(/<div class="breadcrumb">[\s\S]*?<p>([\s\S]*?)<\/p>/), 'breadcrumb');
  const pageTitle = h.match(/<title>([^<]*)<\/title>/);
  const crumbs = bc.split(/\s+(?:>|&gt;)\s+/).map(c => {
    const a = c.match(/href="([^"]+)"[^>]*>([^<]+)</);
    return a ? { label: txt(a[2]), file: a[1].replace(/^\//, '') } : { label: txt(c) };
  });

  return {
    // two originals have no <title>; fall back to the page heading
    title: pageTitle ? pageTitle[1].trim() : txt(one(/<h1>([\s\S]*?)<\/h1>/, 'h1')),
    description: meta('description'),
    keywords: meta('keywords'),
    breadcrumb: crumbs,
    breadcrumbText: txt(bc),
    heading: txt(one(/<h1>([\s\S]*?)<\/h1>/, 'h1')),
    route: txt(one(/<div class="route">([\s\S]*?)<\/div>/, 'route')),
    duration: txt(one(/<div class="duration">([\s\S]*?)<\/div>/, 'duration')),
    days,
    details,
    enquireLabel: eq ? txt(eq[2]) : 'Enquire Now',
    enquireOriginal: eq ? eq[1] : '',
    hero: (h.match(/id="innerpagetopimg"[\s\S]*?<img[^>]*src="([^"]+)"/) || [, 'india-tours-main.jpg'])[1].replace(/^\/?images\//, '')
  };
}

function write(file, t) {
  const base = file.replace(/\.html?$/i, '');
  const J = v => JSON.stringify(v, null, 2).replace(/\n/g, '\n  ');
  const out = `// Content of https://india-tourism.net/${file} — generated by scripts/import-tour.js.
// Wording unchanged (only runs of whitespace collapsed). Bold parts are bold on the original too.
// Served at /${base}
const site = require('../site');

module.exports = {
  file: ${JSON.stringify(file)},
  url: ${JSON.stringify('/' + base)},
  title: ${JSON.stringify(t.title)},
  description: ${JSON.stringify(t.description)},
  keywords: ${JSON.stringify(t.keywords)},
  heroSrc: site.IMG(${JSON.stringify(t.hero)}),
  heroAlt: 'India Tours',
  nav: site.nav('India Tours', false),
  footCols: site.footCols(),
  listings: require('../listings'),

  // Original: ${t.breadcrumbText}
  breadcrumb: [
${t.breadcrumb.map(c => c.file ? `    { label: ${JSON.stringify(c.label)}, href: site.link(${JSON.stringify(c.file)}) }` : `    { label: ${JSON.stringify(c.label)} }`).join(',\n')}
  ],
  heading: ${JSON.stringify(t.heading)},
  route: ${JSON.stringify(t.route)},
  duration: ${JSON.stringify(t.duration)},

  days: ${J(t.days)},

  details: ${J(t.details)},

  // The original's button goes to ${t.enquireOriginal || '(none)'}; here it opens the enquiry form.
  enquire: { label: ${JSON.stringify(t.enquireLabel)}, href: '/contactus?tour=' + encodeURIComponent(${JSON.stringify(t.heading)}) + '#enquiry' }
};
`;
  fs.mkdirSync(OUT, { recursive: true });
  fs.writeFileSync(path.join(OUT, base + '.js'), out);
  const pricing = t.details.find(b => /pric/i.test(b.title));
  console.log(`${file}: "${t.heading}" | ${t.duration} | ${t.days.length} days | details: ${t.details.map(b => b.title + ' (' + b.items.length + ')').join(', ')}${pricing ? '' : ' | NO PRICING BLOCK'}`);
}

(async () => {
  const args = process.argv.slice(2);
  let local = null, dir = null;
  if (args[0] === '--file') { local = args[1]; args.splice(0, 2); }
  if (args[0] === '--dir') { dir = args[1]; args.splice(0, 2); }   // read <dir>/<page> instead of downloading
  if (!args.length) { console.error('usage: node scripts/import-tour.js [--file saved.html | --dir folder] <page.html> ...'); process.exit(1); }
  let failed = 0;
  for (const file of args) {
    try {
      const html = local ? fs.readFileSync(local, 'utf8')
        : dir ? fs.readFileSync(path.join(dir, file), 'utf8')
        : await (await fetch('https://india-tourism.net/' + file)).text();
      write(file, parse(html, file));
    } catch (e) { failed++; console.error('FAILED ' + file + ': ' + e.message); }
  }
  if (failed) process.exit(1);
})().catch(e => { console.error(e.message); process.exit(1); });
